# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ entropy-emacs ]
  pull_request:
    branches: [ entropy-emacs ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os:
          - macos-latest
          - ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build
        run: |
          ./batch.sh
          export platform=$(echo ${{ runner.os }} | awk '{print tolower($0)}')
          export relname="entropy-emacs_treesit-grammars-${platform}-x64"
          zip -r "${relname}.zip" dist
          sha256sum -b "${relname}.zip" > "${relname}.zip.sha256"
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: "2023-01-30 Mon 15:20:17"
          draft: true
          files: |
            entropy-emacs_treesit-grammars-*.zip
            entropy-emacs_treesit-grammars-*.zip.sha256
