# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ entropy-emacs ]
  pull_request:
    branches: [ entropy-emacs ]
  schedule:
    # build test every day once for tracking modules updates
    - cron:  '0 0 * * 1'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: write

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os:
          # FIXME: remove macos temporarily since its github action
          # image as no docker support
          #
          # - macos-latest
          - ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set Env (Top)
        run: |
          echo "RELEASE_DATE=$(date -u +'%Y%m%d%H%M%S')" >> ${GITHUB_ENV}
          echo "RELEASE_VERSION=$(cat version)"          >> ${GITHUB_ENV}
      - name: Set Env (Tag)
        run: |
          echo "RELEASE_TAGNAME=CI/${{ github.ref_name }}/v${{ env.RELEASE_VERSION }}/${{ env.RELEASE_DATE }}" >> ${GITHUB_ENV}
      - name: Install coreutils for macOS
        if: matrix.os == 'macos-latest'
        run: brew install coreutils
      - name: Build
        run: |
          ./batch.sh
          export platform=$(echo ${{ runner.os }} | awk '{print tolower($0)}')
          export relname="entropy-emacs_treesit-grammars-${platform}-x64"
          zip -r "${relname}.zip" dist
          sha256sum -b "${relname}.zip" > "${relname}.zip.sha256"
      - name: "Create latest pre-release tag"
        uses: rickstaa/action-create-tag@v1
        id: "tag_create"
        with:
          tag: ${{ env.RELEASE_TAGNAME }}
          tag_exists_error: true
          no_verify_tag: false
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          name: "PreBuilt (CI: dev) ${{ env.RELEASE_VERSION }}/${{ env.RELEASE_DATE }}"
          tag_name: ${{ env.RELEASE_TAGNAME }}
          prerelease: true
          draft: true
          files: |
            entropy-emacs_treesit-grammars-*.zip
            entropy-emacs_treesit-grammars-*.zip.sha256
